import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Kinetic Sanctuary Design System
        "surface":                  "var(--surface)",
        "surface-dim":              "var(--surface-dim)",
        "surface-bright":           "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low":    "var(--surface-container-low)",
        "surface-container":        "var(--surface-container)",
        "surface-container-high":   "var(--surface-container-high)",
        "surface-container-highest":"var(--surface-container-highest)",
        "surface-variant":          "var(--surface-variant)",
        "surface-tint":             "var(--surface-tint)",
        "on-surface":               "var(--on-surface)",
        "on-surface-variant":       "var(--on-surface-variant)",
        "outline":                  "var(--outline)",
        "outline-variant":          "var(--outline-variant)",
        "background":               "var(--background)",
        "on-background":            "var(--on-background)",
        "inverse-surface":          "var(--inverse-surface)",
        "inverse-on-surface":       "var(--inverse-on-surface)",
        // Primary
        "primary":                  "#c0c1ff",
        "primary-container":        "#4b4dd8",
        "primary-fixed":            "#e1e0ff",
        "primary-fixed-dim":        "#c0c1ff",
        "on-primary":               "#1000a9",
        "on-primary-container":     "#d9d8ff",
        "on-primary-fixed":         "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary":          "#494bd6",
        // Secondary
        "secondary":                "#4edea3",
        "secondary-container":      "#00a572",
        "secondary-fixed":          "#6ffbbe",
        "secondary-fixed-dim":      "#4edea3",
        "on-secondary":             "#003824",
        "on-secondary-container":   "#00311f",
        "on-secondary-fixed":       "#002113",
        "on-secondary-fixed-variant":"#005236",
        // Tertiary
        "tertiary":                 "#ffafd3",
        "tertiary-container":       "#a63274",
        "tertiary-fixed":           "#ffd8e7",
        "tertiary-fixed-dim":       "#ffafd3",
        "on-tertiary":              "#620040",
        "on-tertiary-container":    "#ffcee2",
        "on-tertiary-fixed":        "#3d0026",
        "on-tertiary-fixed-variant":"#85145a",
        // Error
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
        // Legacy shades (backward compat)
        "primary-50":  '#eef2ff',
        "primary-100": '#e0e7ff',
        "primary-200": '#e1e0ff',
        "primary-400": '#818cf8',
        "primary-500": '#c0c1ff',
        "primary-600": '#4b4dd8',
        "primary-700": '#4338ca',
        "success-50":  '#ecfdf5',
        "success-400": '#34d399',
        "success-500": '#4edea3',
        "success-600": '#00a572',
        "warning-400": '#fbbf24',
        "warning-500": '#f59e0b',
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
        mono:     ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        'card':       '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)',
        'card-hover': '0 4px 12px 0 rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        'ambient':    '0 40px 80px -20px rgba(192, 193, 255, 0.08)',
        'sidebar':    '40px 0 40px -15px rgba(192, 193, 255, 0.06)',
        'glow':       '0 0 20px rgba(192, 193, 255, 0.4)',
        'glow-green': '0 0 20px rgba(78, 222, 163, 0.3)',
      },
      keyframes: {
        'caret-blink': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-10px)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.15' },
          '50%':      { opacity: '0.3' },
        },
      },
      animation: {
        'caret-blink': 'caret-blink 1s ease-in-out infinite',
        'float':       'float 3s ease-in-out infinite',
        'pulse-glow':  'pulse-glow 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
export default config;
